### ISSUE TITLE
Create "Members" section

### ISSUE THREAD

**Issue by PaHorton** [sunhacksio/website#15]
either make an html page that displays this information or create a new notion database that must be manually populated with info

**Comment by EdmundDong** [comment]
I tried to set something up, but there's no way for us to do this easily with our current team directory setup. 
The problem is that data from a database can only be shared when the entirely of the database is shared publicly. 
I tried to setup a relation that looked up the specific information we wanted from the team directory database and even though it pulls the information fine in notion, the information would not be shown on the public page. 

Suggestion:
1. Create a new database for private info
Create a private database for private information (i.e. phone numbers and emails).
Lookup information from the private database to be shown in our internal team directory.
Create a page with a view of the linked directory with the public information.

2. Wait for notion's api to release and try to see if we can pull the data ourselves without having to change our databases
https://www.notion.so/api-beta

**Comment by EdmundDong** [comment]
completed last year
